### ISSUE TITLE
Cannot make it work properly

### ISSUE THREAD

**Issue by adrianrise** [c4urself/bump2version#10]
Hi there,

I am trying to make it work to fit our needs but obviously I must be doing something wrong.

The idea of our versioning is the next:

Major.Minor.Patch-Prepatch == 1.1.0-0

How do I have to configure the bumpversion.cfg to make it work?
Currently my config is the following:

```
[bumpversion]
current_version = 3.1.0
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\-(?P<release>\d+))?
serialize =
	{major}.{minor}.{patch}-{release}
	{major}.{minor}.{patch}

[bumpversion:file:setup.py]
```
But when I do the following command:

`bump2version --config-file bumpversion.cfg --current-version $(python setup.py --version) release setup.py --allow-dirty`

I get this version on my setup.py:

`'version': '3.1.0-1-1'`

Could someone please explain what am I doing wrong? Or what is missing?

Thank you!

**Comment by piksel** [comment]
You are using setuptools to get the current version instead of reading it from the `setup.py` file directly.

I get this warning running a mock-up of your configuration:
```
/usr/lib/python3/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '3.1.0-1' to '3.1.0.post1'
  normalized_version,
```

Just skip the `--current-version` option and it should work correctly.

**Comment by c4urself** [comment]
@adrianrise could you confirm you've gotten it working?
