### ISSUE TITLE
About Homebrew formula 

### ISSUE THREAD

**Issue by chenrui333** [c4urself/bump2version#102]
Just FYI, I have just made [a formula upgrade](https://github.com/Homebrew/homebrew-core/pull/47379) to track this maintained fork for the time being.

Once the ownership got sorted out, it would be great that we keep the homebrew formula up to date as well.

**Comment by chenrui333** [comment]
Also related to https://github.com/c4urself/bump2version/issues/86

**Comment by c4urself** [comment]
thanks @chenrui333 much appreciated, I'll add to the docs that this is brew installable.
