### ISSUE TITLE
How to get current version properly?

### ISSUE THREAD

**Issue by GreatBahram** [c4urself/bump2version#103]
Hello there,

I was wonder if there is an option to get only current version without using any kind of hack?
I supposed `--list` would do this, but it was completely different thing! is there any plan to add something like `--show-version`?

**Comment by florisla** [comment]
This is planned, you can follow #57 to follow the progress.

**Comment by florisla** [comment]
Closing to keep all status updates in development issue #57.

**Comment by GreatBahram** [comment]
Thanks
