### ISSUE TITLE
Remove old and external branches from the main repository

### ISSUE THREAD

**Issue by florisla** [c4urself/bump2version#104]
Hi,

These branches should be removed from the github repository:

[issue-11](https://github.com/c4urself/bump2version/tree/issue-11) (merged)
[fix-test-cases](https://github.com/c4urself/bump2version/tree/fix-test-cases) (merged)
[0.5.6](https://github.com/c4urself/bump2version/tree/0.5.6) (not actually version 0.5.6; there is a suitable tag)

I'd also recommend to remove these branches since they should be developed in contributor's repos and not here:

[appveyor](https://github.com/c4urself/bump2version/tree/appveyor)
[issue-60](https://github.com/c4urself/bump2version/tree/issue-60)
[multi-os](https://github.com/c4urself/bump2version/tree/multi-os)

**Comment by ekohl** [comment]
Done, thanks!
