### ISSUE TITLE
Drop Python 2

### ISSUE THREAD

**Issue by ekohl** [c4urself/bump2version#105]
At the time of writing Python 2 goes EOL in 19 days according to https://pythonclock.org/ and IMHO we should follow suit.

I'm proposing we drop Python 2 and do a major version bump. The minimal version of Python 3 should be 3.6 which will allow us to use features like f-strings.

There are some `PendingDeprecationWarning` and we should drop those while we do a major version bump.

Any concerns?

**Comment by florisla** [comment]
An argument contra: many Linux distributions still in support do not natively offer Python 3.6.

See e.g. https://wiki.ubuntu.com/Releases: Ubuntu Xenial 16.04 LTS still has 16 months of support left and comes with Python 3.5.1.

On the other hand
* I like f-strings
* Many users will know how to move to a more recent Python anyway
* Dropping support will not break anything -- it just blocks an upgrade path for the users
* Django is also 3.6 only

I am +1 on going 3.6.

**Comment by florisla** [comment]
Another data point: https://devguide.python.org/#status-of-python-branches
Python.org drops Python 3.5 support in september 2020.

**Comment by hugovk** [comment]
Please see PR https://github.com/c4urself/bump2version/pull/108.

**Comment by c4urself** [comment]
I'm against moving to 3.6+ until 3.5 is officially dropped.

**Comment by ekohl** [comment]
Somehow I was under the impression that 3.5 was EOL already. Not sure where that came from, but if it's supported, I agree we should also support it.

**Comment by florisla** [comment]
Python 2.7 is dropped in #108 .
