### ISSUE TITLE
Support processing a file multiple times

### ISSUE THREAD

**Issue by florisla** [c4urself/bump2version#111]
For a certain file I needed to have two different serializations.

Turns out you can do that using `bumpversion.cfg` as long as the file name is written differently each time.  I'm using a `./` prefix here.

    [bumpversion:file:version.txt]
    search = Version: {current_version}
    replace = Version: {new_version}
    parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
    serialize = {major}.{minor}.{patch}

    [bumpversion:file:./version.txt]
    search = Release: {current_version}
    replace= Release: {new_version}
    parse = (?P<major>\d+)-(?P<minor>\d+)-(?P<patch>\d+)
    serialize = {major}-{minor}-{patch}

Is this something we should document?  I *think* this can solve #43 and #4, although it's perhaps not a very intuitive solution for those issues.

Thought: we could extend the `[bumpversion:file]` syntax to support multiple editions to make this more readable, like

    [bumpversion:file:version.txt:version]
    ...
    [bumpversion:file:version.txt:release]
    ....

**Comment by c4urself** [comment]
There's a Helm question on this as well, in general it feels like a bit of a code smell if you have multiple variables that reference a version and so I think it makes sense to make it a duplicate action in the .bumpversion.cfg as well; that is, have multiple sections for each time you want to search/replace in the same file.

**Comment by florisla** [comment]
I'll rebase once the Python 2.7 drop is merged.

**Comment by florisla** [comment]
Thoughts about the new `file(variant)` syntax?
