### ISSUE TITLE
Question: how to use parse to deal only with major version?

### ISSUE THREAD

**Issue by padamstx** [c4urself/bump2version#113]
Hi, after discovering this more up-to-date fork of the original bumpversion project, I'm in the process of switching over to it and I have a question.

I already use bumpversion to maintain version #'s in a few files, where the version # is the full version # (e.g. 3.2.5).   I have a scenario where I want to maintain only the major version # within a go.mod file.   Within this file I have a module directive like this:
```
module github.com/IBM/go-sdk-core/v3
```
where "3" represents the current major version of the package.   I'd like to be able to configure bumpversion to bump this to "v4" when the next major version is created.
It looks like I could maybe use a combination of the "parse" and "search" directives within a `[bumpversion:file:...]` section in my cfg file.    Anyone done this before?
It would be great if the README contained an example of this (after figuring this out, I would be happy to submit a PR for that).
Thanks in advance!

**Comment by ekohl** [comment]
I think you should be using `parse` and `serialize` and set those on for a specific file.

**Comment by florisla** [comment]
I just wrote an example config that does exactly this in #43 .

Here it is, adapted to your situation and verified to work...
If you make the pull request you promised ;-)

`.bumpversion.cfg`:

    [bumpversion]
    current_version = 4.1.0

    [bumpversion:file:version.txt]

    [bumpversion:file:go-sdk.txt]
    parse = (?P<major>\d+)
    serialize = {major}
    search = module github.com/IBM/go-sdk-core/v{current_version}
    replace = module github.com/IBM/go-sdk-core/v{new_version}

`version.txt`:

    4.1.0

`go-sdk.txt`:

    module github.com/IBM/go-sdk-core/v4

Testing it out:

    >>> bumpversion --verbose minor
    current_version=4.1.0
    new_version=4.2.0
    >>> bumpversion --verbose major
    current_version=4.2.0
    new_version=5.0.0
    >>> bumpversion --verbose minor
    current_version=5.0.0
    new_version=5.1.0
    >>> cat go-sdk.txt
    module github.com/IBM/go-sdk-core/v5

**Comment by padamstx** [comment]
> Here it is, adapted to your situation and verified to work...
> If you make the pull request you promised ;-)

Thanks a bunch for working up this example!   I will do the README PR, later this week.  I promise! :)

**Comment by padamstx** [comment]
@florisla I'm ready to add a "go.mod" example to the project's README file.   I think there are two options for this:
1. add a brief example as part of the discussion around the `parse` option
2. add a new paragraph underneath `Using bumpversion in a script` with heading something like `Using bumpversion to maintain a go.mod file`

I'm sort of leaning toward #2.   Do you have a preference?

**Comment by florisla** [comment]
I would go for #2 and move the examples to a separate file (or a repository folder) once we have more of them.
