### ISSUE TITLE
Message CLI param doesn't support unicode characters

### ISSUE THREAD

**Issue by jpettit** [c4urself/bump2version#123]
Use a message string with a unicode character: `→`

`$ bump2version ... --message 'CI/CD build {current_version} → {new_version}'`

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by jpettit** [comment]
Feel free to disregard.  This was on Python 2.7

**Comment by florisla** [comment]
So it works fine on Python 3 for you?

**Comment by jpettit** [comment]
Yes, Python 3.7.0 works fine in Ubuntu LTS 16.
