### ISSUE TITLE
Dynamically generate an dashed line based on version string length

### ISSUE THREAD

**Issue by sdementen** [c4urself/bump2version#126]
I would like to convert the follwing in my changelog with bump2version

```
(dev)

* my change log item

```

```
0.1.13 (2020-01-25)
-------------------

* my change log item

```

I have tried something like
```
[bumpversion:file:CHANGELOG.rst]
search = (dev)
replace = {new_version} ({now:%Y-%m-%d})
	"{'-' * len(new_version)}--{'-' * len(now.strftime('%Y-%m-%d'))}-"

```
but bump2version uses string format and not f-string.

Is there some way to do this ?

**Comment by florisla** [comment]
So you want to influence the width of the dashed line based on the width of the version string...

Bump2verson does not use f-strings because we still support Python 3.5.

I don't think there's a way to achieve the desired effect in bump2version itself.

Possible workarounds
* Serialize the version numbers with fixed width  and keep the underline width constant.
```
 0. 1.13
12.11. 1
```

* Calculate the 'width of the underline' externally and supply the underline dashes as an environment variable

```
    replace = {new_version} ({now:%Y-%m-%d})
        {$VERSION_STRING_UNDERLINE}
```

**Comment by sdementen** [comment]
Indeed, great workaround.
What is needed to avoid having the current version in the changelog being updated when bumping?

**Comment by florisla** [comment]
`--dry-run`

You can combine it wit `--list`.

**Comment by sdementen** [comment]
Sorry, I wasn't clear.
In the changelog, for each version, there is a list of changes.
If I am at version 1.1.4 and developing for 1.1.5, I write in the changelog, "(dev)" (not 1.1.5.).
When I bump the version, I want (dev) to be converted to 1.1.5 but the old 1.1.4 should stay unchanged.
For the search field, I write "(dev)" and it works as expected if the string "(dev)" is in the changelog file (I.e. "(dev)" is replaced by "1.1.5". However, if the string "(dev)" is not in the changelog, then it is the string "1.1.4" (that should not be changed in the changelog file) that gets updated to "1.1.5"

**Comment by florisla** [comment]
Ah yes, if `search` is not found then it simply searches for `{current_version}`.  There's no way around that currently.

I just opened #127 to fix this.

**Comment by sdementen** [comment]
for the record, I finally end up with:
```
[bumpversion:file:CHANGELOG.rst]
search = (dev)
replace = {new_version:<8} ({now:%Y-%m-%d})
	---------------------

```
which works (as long as `(dev)` exists in the changelog, ie not hit by #127 )

**Comment by florisla** [comment]
Good find to use `<8` formatting.

I guess you can now move the dashed line out of your config file, into the chanelog.

**Comment by sdementen** [comment]
I keep the dashed line in the config to avoid needing to copy it each time, I just type "(dev)" and I am good to go
