### ISSUE TITLE
Documented Example Versus Help/Error

### ISSUE THREAD

**Issue by tinjaw** [c4urself/bump2version#130]
Documentation provides the following example:

>bump2version [options] part [file]

however, when I run, I get.

>bump2version minor
usage: bumpversion [-h] [--config-file FILE] [--verbose] [--list]
                   [--allow-dirty] [--parse REGEX] [--serialize FORMAT]
                   [--search SEARCH] [--replace REPLACE]
                   [--current-version VERSION] [--dry-run] --new-version
                   VERSION [--commit | --no-commit] [--tag | --no-tag]
                   [--sign-tags | --no-sign-tags] [--tag-name TAG_NAME]
                   [--tag-message TAG_MESSAGE] [--message COMMIT_MSG]
                   [--commit-args COMMIT_ARGS]
                   part [file [file ...]]
bumpversion: error: the following arguments are required: --new-version

It kinda defeats the purpose of automation if I am required to provide the new version number.

**Comment by florisla** [comment]
Hi, If you don't supply the `file` argument then you need to use a `.bumpversion.cfg` configuration file to specify it.

Otherwise, bumpversion does not know which file to modify.

Here's a real example:

File `version.txt`:

    4.2.8

Bump the `major` part.

Command:

    bumpversion --current-version "4.2.8" major "version.txt"

Produces `version.txt`:

    5.0.0

When issue #120 gets fixed, we will be offering lots of examples that clarify usage like this.

**Comment by tinjaw** [comment]
> Hi, If you don't supply the `file` argument then you need to use a `.bumpversion.cfg` configuration file to specify it.
> 
> Otherwise, bumpversion does not know which file to modify.

I forgot to mention that I am using a .bumpversion.cfg file.

**Comment by florisla** [comment]
Please share the content of your configuration file.

**Comment by tinjaw** [comment]
Typed the file name. Sorry.

**Comment by florisla** [comment]
So you had a `[bumpversion:file:]` section but with a non-existing file in it?  In that case, we should provide a better error message.

**Comment by tinjaw** [comment]
No. I had bump2version.cfg.

**Comment by florisla** [comment]
That explains a lot :-)
