### ISSUE TITLE
{new_version} not available in search

### ISSUE THREAD

**Issue by chfast** [c4urself/bump2version#136]
This config does not work, I get `KeyError` of `"new_version"`.
```
search = {new_version}
```

It is also unclear if parsing/serializing is done for every file individually or if the result values are taken from main config if `parse` and `serialize` sections are not present in `[file]` section.

Why this can be useful?
```
search = {new_version} - unreleased
replace = {new_version} - {utcnow:%Y-%m-%d}
```

**Comment by florisla** [comment]
You have to search for `current_version`, not `new_version`.

If you don't specify `parse` or `serialize` then those settings are taken from the main configuration.

**Comment by chfast** [comment]
> You have to search for `current_version`, not `new_version`.

I want to search for `{new_version}` as stated.

**Comment by florisla** [comment]
That's not possible... The `new_version` is not yet known at that point.

First, `current_version` is searched and only then is this used to calculate `new_version`.

**Comment by florisla** [comment]
To clarify, searching `current_version` is done for all files, and bumpversion enforces that all the files have the same version number.

**Comment by florisla** [comment]
I'm going to classify this as an unsupported use case.
