### ISSUE TITLE
Behavior if used with --current-version and --new-version

### ISSUE THREAD

**Issue by 4hopp** [c4urself/bump2version#140]
If bump2version is used with both `--current-version` and `--new-version` (or only `--new-version`, but the current version can be retrieved from the config file) it seems like the `part` argument is not used at all, though it is required. Is this assumption correct?

Example:

```
bump2version --current-version 2.0.0 --new-version 2.1.0 major
```

(My assumption is, that this would result in a minor bump, going from 2.0.0 to 2.1.0 and ignoring the argument `major`.)

If the `part` argument _is_ used by bump2version in those cases in any way, then it should be clarified how `part` affects the result.

If it _is not_ used, then the user should have the option to omit `part`. If they decide to use `part` however, then bump2version should check for consistency. (E.g. Is this really a major/minor/patch bump?)

**Comment by florisla** [comment]
You're right, `part` is not used at all, even though it is  a required argument.

In many cases you can use `a-non-existing-part` as the `part` argument, and it will work just as well.

Issue #22 is tracking this.
