### ISSUE TITLE
Is there a release planned soon?

### ISSUE THREAD

**Issue by lamdav** [c4urself/bump2version#153]
It's been a while since `v1.0.0` was released and there has been several bug fixes such as enable logging and avoiding search defaults that would be nice to released on pypi and avoid having to install from github. Is there a release plan soon or roadmap? 

Thanks.

**Comment by c4urself** [comment]
Agreed, we'll try to get a release out by the end of the month, no promises though, kind of a best-effort thing after $dayjob.

**Comment by sercxanto** [comment]
I use bump2version heavily and I would also appreciate it if there would be an offical release with all the bug fixes (especially the avoid search default issue) so far.

@c4urself If there is anything I can support for preparing the release, please let me know.

**Comment by c4urself** [comment]
great to hear you're using it! just put out a release today, thanks.
