### ISSUE TITLE
Add PyCalVer to RELATED.md

### ISSUE THREAD

**Issue by mbarkhau** [c4urself/bump2version#157]
I prepared a blurb, for your consideration.

* [PyCalVer](https://gitlab.com/mbarkhau/pycalver) is also a tool to bump version numbers, but for projects which do [calendar versioning](https://calver.org/)

```markdown
* [PyCalVer](https://gitlab.com/mbarkhau/pycalver) is also a tool to bump version numbers, but for projects which do [calendar versioning](https://calver.org/)
```

@florisla since you assigned yourself #151 (a similar issue), maybe you want to take this, or should I just open a PR?

**Comment by ekohl** [comment]
Please open a PR for this.
