### ISSUE TITLE
README on pypi.org not readable

### ISSUE THREAD

**Issue by vlcinsky** [c4urself/bump2version#17]
https://pypi.org/project/bump2version/ shows content of README, which is broken.

there seem to be two reasons:
- the value for `long_description` is provided as bytes and not as a string
- the content if formatted as markdown and not reStructuredText

With refactored https://pypi.org well readable README can serve as great presentation of the package and `bump2version` can definitely do better.

If reStructuredText seems too difficult, I volunteer to write it properly. It is not so difficult and such great tool as bump2version deserves good presentation.

**Comment by anthrotype** [comment]
You can also use github flavoured markdown now, if you set the new long_description_type field.

**Comment by c4urself** [comment]
@vlcinsky -- thanks for noticing! I really much prefer Markdown and actually rewrote the Readme to markdown recently -- much easier to maintain for me. Let's try @anthrotype's suggestion.

**Comment by vlcinsky** [comment]
Good @c4urself . You are  commander of this ship. As I have never used `long_description_type`, I leave that modification to other experts.

**Comment by anthrotype** [comment]
https://github.com/pypa/sampleproject/blob/6a2444b88f48eaa1cf3a2f32fe8bbed8dad82801/setup.py#L70

**Comment by ekohl** [comment]
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi is the complete story. You also need somewhat new tools to upload the release to send the correct metadata.

**Comment by micahjsmith** [comment]
The correct option is `long_description_content_type="text/markdown"`

**Comment by Mattwmaster58** [comment]
sooo what are we waiting for here? A PR

**Comment by Mattwmaster58** [comment]
screw it, why not? #24

**Comment by florisla** [comment]
@c4urself Did you upgrade your twine before uploading 0.5.10 to PyPI?

The layout there still seems to be rendered as plain text, not as proper Markdown.
This even though `dist-info/METADATA` in the Wheel file contains the correct `Description-Content-Type`.

Also, it seems there's no source distribution (`.tar.gz`) uploaded at https://pypi.org/simple/bump2version/ .

**Comment by c4urself** [comment]
@florisla -- I did! I installed `twine==1.11.0` and ran the `twine upload` command, see: https://github.com/c4urself/bump2version/blob/master/Makefile#L12 -- as far as the tar.gz -- I indeed only uploaded the wheel as I thought that's the "future" now?

**Comment by ekohl** [comment]
@c4urself it is good practice to upload both IMHO

**Comment by ekohl** [comment]
@c4urself you also had `setuptools>=38.6.0` and `wheel>=0.31.0` installed?

**Comment by florisla** [comment]
Note: the latest release of `twine` has a 'check' command, which checks if the README will render correctly on PyPI.  See [twine docs](https://pypi.org/project/twine/).

For the next release, I would recommend:

    pip install --upgrade pip
    pip install --upgrade setuptools
    pip install --upgrade wheel
    pip install --upgrade twine
    pip install readme_renderer[md]
    setup.py build sdist
    setup.py build bdist_wheel
    twine check dist/*
