### ISSUE TITLE
Is it possible to set current_version automatically?

### ISSUE THREAD

**Issue by dudicoco** [c4urself/bump2version#207]
Hi,

Is it possible to locate the current version automatically within a file instead of specifying it?

For example, if I have a file with the content `1.0.0` I would expect `bump2version` to automatically grep the current version and bump it accordingly.

Thanks

**Comment by dudicoco** [comment]
@florisla perhaps you can give input here?

**Comment by florisla** [comment]
Hi,

Currently this is not possible.  It is being considered for a future release though.

_Don't wait for it_, this could take a while.

**Comment by dudicoco** [comment]
Thanks @florisla.

As a workaround, i've did the following:
```
bump2version --allow-dirty patch VERSION --current-version `cat VERSION`
```

**Comment by florisla** [comment]
Thanks for sharing the workaround!

Closing this since the feature is tracked in #185.
