### ISSUE TITLE
Consolidate CI into github actions

### ISSUE THREAD

**Issue by clbarnes** [c4urself/bump2version#227]
travis-ci.org is dead, I couldn't find the builds on travis-ci.com, and appveyor doesn't support python 3.9, which has been out for 10 months (with dev builds far pre-dating that). In general, maintaining multiple CI configs is a pain. GHA would let us test on linux, windows, and mac with relatively little pain in one config file, with better python support. We can even keep delegating to tox: https://github.com/ymyzk/tox-gh-actions

**Comment by florisla** [comment]
Hi, this sounds very good.

Would you be willing to make a PR for this?
