### ISSUE TITLE
Add --dry-run option

### ISSUE THREAD

**Issue by vlotorev** [c4urself/bump2version#23]
Dry-run mode is useful:
* for development and debugging .bumpversion.cfg
* for continuous integration in tox.ini file: implemented as tox environment it could check that files specified in cfg file are parsed and *could* be replaced with version correctly.

Dry-run should not modify any files.

**Comment by jhinAza** [comment]
Hello, I think what you need is already implemented in the library.
As it's explained [here](https://github.com/c4urself/bump2version#command-line-options)
```
(venv) jhinaza@jhinaza-laptop:~/projects/tests$ bumpversion minor --verbose --dry-run
Reading config file setup.cfg:
[bumpversion]
current_version = 1.3.0
commit = True
tag = True

[bdist_wheel]
universal = 1

[metadata]
description-file = README.md


Parsing version '1.3.0' using regexp '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
Parsed the following values: major=1, minor=3, patch=0
Attempting to increment part 'minor'
Values are now: major=1, minor=4, patch=0
Dry run active, won't touch any files.
Parsing version '1.4.0' using regexp '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
Parsed the following values: major=1, minor=4, patch=0
New version will be '1.4.0'
Asserting files  contain the version string:
Would write to config file setup.cfg:
[bumpversion]
current_version = 1.4.0
commit = True
tag = True

[bdist_wheel]
universal = 1

[metadata]
description-file = README.md
```
Dry run is more useful using the `--verbose` option, if you run twice the above command you will notice the output it's the same, and if you check the files they will not be modified, and there will be not changes in the repository

**Comment by vlotorev** [comment]
thanks for pointing this.
I checked and it works as expected.
I'm sorry for the noise.
