### ISSUE TITLE
A bit too aggro on the version parsing

### ISSUE THREAD

**Issue by jakethedev** [c4urself/bump2version#25]
Hey there, love the work you're doing to keep this alive

I've noticed, in my adventures setting up PEX builds for python apps, that any edition of bumpversion (bump2version, advbumpversion, etc) will aggressively match versions from setup.cfg in the listed files. In our case, setup.py is one of those files (normal stuff) and our install_requires can regularly list exact versions of other apps (abnormal but supported). Bumpversion likes to Loki it up in there. 

Let's say my setup.cfg looks like this, a real basic one:
```bash
>> cat setup.cfg 
[bumpversion]
current_version = 1.0.2
commit = False
tag = False
tag_name = {new_version}

[bumpversion:file:setup.py]

[bumpversion:file:myapp/__init__.py]
``` 

And my setup.py looks like this:
```python
from setuptools import setup
__version__ = '1.0.2'

setup(
    name='myapp',
    version=__version__,
    install_requires=[
        'Flask==1.0.2'
    ]
    ...other useful irrelevant stuff....
)
```

If I run bumpversion on this project, it bumps the Flask version as well since it's the same "version", and causes our CICD to burst into flames.

What would it take to get a config/cli option for "keyword"? Like in setup.cfg, we can say what pattern our version follows, so it would be equally awesome to list a keyword that will always be found on the lines with the version, such as "version", so bumpversion only replaces versions found on lines that contain the keyword.

**Comment by ekohl** [comment]
I think a solution as @florisla suggests is the best one. It can even be useful to know the version at runtime.

**Comment by jakethedev** [comment]
That's a solid workaround really, we have a decent bit of code built around the setup.py containing the version though and people are already starting to get used to the expected architecture, but it's really probably best to hit the growing pains while they're still small. A version.py might solve a couple problems for us down the road anyways

So, touche 😄 Still think it would be a nice feature but I can dig it if it's not happenin

**Comment by jakethedev** [comment]
The golden fleece!

Awesome, thanks so much for looking into it!
