### ISSUE TITLE
Offer: take on future development with bump-my-version

### ISSUE THREAD

**Issue by coordt** [c4urself/bump2version#268]
Hello,

I made a fully backward-compatible refactor of this code at [bump-my-version](https://github.com/callowayproject/bump-my-version) in hopes of making bugs easier to fix and new features easier to implement.

Since it seems active development has waned here (no judgment!) I would offer that project as its spiritual successor.

Please mention it in the README, if you like.

**Comment by ekohl** [comment]
I can't speak for other maintainers, but I don't have the time to work on bump2version at all anymore. I feels bad, but it's the reality. So for me it's perfectly ok to promote something else.

This is perhaps more up to @c4urself, but I think we should consider adding more maintainers. Or even merge your changes as a new major version. That saves the community of manually finding a replacement and provide a regular upgrade path.

**Comment by florisla** [comment]
Hi @coordt, this is great to see.

Starting with a clean sheet was the best option in my opinion.

How far did you go in ensuring backwards compatibility?  Are all the old unit tests covered?

**Comment by coordt** [comment]
I ported over all the old unit tests that made sense. Some of the unit
tests didn't make sense with the new code.

As far as I can tell, it _should_ be 100%. Would need to have some
verification by outside parties.

**Comment by kdeldycke** [comment]
@coordt is doing an amazing job with his new [`bump-my-version`](https://github.com/callowayproject/bump-my-version) project.

It is actively maintained, modern, fixes lots of issues that were pending for the last 3~4 years and already adds features that were requested as far back as the original [bumpversion](https://github.com/peritus/bumpversion) project.

I propose to add a warning to bump2version's `README.md` and redirect users to `bump-my-version`.

What do you think?

**Comment by kdeldycke** [comment]
I just made a proposition at: https://github.com/c4urself/bump2version/pull/272

**Comment by kdeldycke** [comment]
I also volunteer to make a final release of `bump2version` on PyPi if I get the right admin permissions.

I already had to do this kind of work when I renamed my `maildir-deduplicate` project to `mail-deduplicate`. See:
- The final release with a warning: https://pypi.org/project/maildir-deduplicate/
- https://github.com/kdeldycke/mail-deduplicate/commit/ebfafa153562e093fb060df7d44999b327bfa93d

**Comment by kdeldycke** [comment]
Also made a PR to `bumpversion`: https://github.com/peritus/bumpversion/pull/219 😁

**Comment by florisla** [comment]
Thanks, this needs to happen.

**Comment by florisla** [comment]
Hi @kdeldycke , it seems I have ignored your offer to build a final release of bump2version.  Sorry about that!

Does the offer still stand?

I think part of the user base is still not aware of the existence of bump-my-version .

**Comment by kdeldycke** [comment]
> Hi [@kdeldycke](https://github.com/kdeldycke) , it seems I have ignored your offer to build a final release of bump2version. Sorry about that!
> 
> Does the offer still stand?
> 
> I think part of the user base is still not aware of the existence of bump-my-version .

Yeah! Let's do that! I guess all I need is access on the repository and the PyPi release. Same username in both case: `kdeldycke`.

**Comment by florisla** [comment]
I don't have permissions myself to add you as a co-maintainer.

All I can do is approve a pull request.

For uploading, we'll have to defer to ekohl or c4urself, but that should be doable.
