### ISSUE TITLE
Can I use a tuple as version format, but still use a completely different format for tags?

### ISSUE THREAD

**Issue by florisla** [c4urself/bump2version#28]
Hi,

My version format looks like

    # tuple that is easy to compare
    __version_info__ = (1, 4, 2)
    # string version derived from tuple, as the standard __version__ attribute
    __version__ = '.'.join(map(str, __version_info__))

Parsing and serialization of the tuple works fine, but the tag name for Git becomes 'v(1, 4, 2)' while of course I'd want 'v1.4.2'.

My first reaction was to set `tag_name` to '`v{major}.{minor}.{patch}`', but the parts (major/minor/patch) can not be used in tag_name.  Is this on purpose?

What are my options if I want to have a different serialization in my files versus in the tag name?

I do have a branch which allows `tag_name = v{major}.{minor}.{patch}` -- let me know if that would fit as a merge request.
https://github.com/florisla/bump2version/tree/all-parts-in-strings

**Comment by ekohl** [comment]
Have you had a look at `parse`? You can override the regex it uses to parse the version string. This probably needs to account for the regular serialized version as well for README files but I think it can get you where you want. The alternative is to split a string to a tuple in Python code, but that's probably uglier than from a data structure to a string.

**Comment by florisla** [comment]
I'm already using ´parse´, but I only just now realized that you can have a *different* ´parse´and ´serialize´ per file.

I think that solves my use case: use the tuple-based ´parse´ and´serialize´ in the config for one specific file, and use the standard (global) ones for ´tag_name´.

**Comment by florisla** [comment]
Confirmed that this is working.

    [bumpversion]
    current_version = 1.4.2

    [bumpversion:file:myproject/__version__.py]
    serialize = ({major}, {minor}, {patch})
    parse = \((?P<major>\d+),\s(?P<minor>\d+),\s(?P<patch>\d+)\)
