### ISSUE TITLE
Rename package too?

### ISSUE THREAD

**Issue by ionelmc** [c4urself/bump2version#3]
Would be nice to also rename package so you can have bumversion and bump2version installed side-by-side.

**Comment by anthrotype** [comment]
Why would one want to do that? bump2version supersedes bumpversion, i.e. covers all of its functionality and now also installs a `bumpversion` console script.
I actually like the fact that I can use it as a drop-in replacement for the former without having to change my scripts that use it, but only the requirements.txt.

**Comment by ionelmc** [comment]
Well I guess to try them both and see what's fixed.

It's a unfortunate situation when a maintainer wants to kill a project and not give up ownership, all solutions will have downsides.

**Comment by ionelmc** [comment]
Then again, I can use virtualenv or something. Nevermind.
