### ISSUE TITLE
bump2version deletes comments/commented out lines when using setup.cfg

### ISSUE THREAD

**Issue by mfcabrera** [c4urself/bump2version#37]
if using `setup.cfg` and setting up the version configuration, once I use `bump2version part` the version gets updated but all the comments are removed.  

Is this the expected behaviour?

**Comment by mfcabrera** [comment]
Apparently this is impossible to do with standard ConfigParser.
https://stackoverflow.com/questions/21476554/update-ini-file-without-removing-comments

So either another library is used or move the configuration from`setup.cfg` to `.bumpversion.cfg`

**Comment by luzfcb** [comment]
same problem here. 
thanks @mfcabrera, for showing me the workaround:

move the configuration from `setup.cfg` to `.bumpversion.cfg`

**Comment by c4urself** [comment]
Closing as it looks like a workaround has been found. Thanks @mfcabrera.

**Comment by andreoliwa** [comment]
FYI: this package can update .INI files and preserve comments: [pyscaffold/configupdater: 🌴 Parser like ConfigParser but for updating configuration files](https://github.com/pyscaffold/configupdater)
