### ISSUE TITLE
adding custom application tag with version in the part

### ISSUE THREAD

**Issue by shylaharild** [c4urself/bump2version#40]
The part works fine for the values provided in it but I would like to provide a custom value for the releases like application name while working on the branch. Because my repository has templates for multiple applications and I would like to use versioning with that application name while making changes for that particular application.

Example:
Say, `master` branch has version `0.0.1` and I am on a branch taken from the `master` making changes to an application `rabbitmq` templates. So while doing a version on that branch, I would like it to be `0.0.1-rabbitmq00`.

And while merging back to `master`, I want to bump up the version on the master from `0.0.1` to 0.0.2` and lose whatever application name and its counter I have on the branch. 

How do I do it? I cannot use part here the way I want as it increments the part from one application to another if I list those application names as custom values.

```
[bumpversion]
current_version = 0.0.0
commit = True
tag = True
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\-(?P<application>[a-z]+)(?P<rc>\d+))?
serialize =
	{major}.{minor}.{patch}-{application}{rc}
	{major}.{minor}.{patch}

[bumpversion:part:application]
optional_value = devops
values =
	rabbitmq
	lambda
        codedeploy
	devops

[bumpversion:part:rc]

[bumpversion:file:METADATA]
```

**Comment by florisla** [comment]
If I understand your question, you want to increment the `rc` part from `00` to `01` to `02` and so on, and have it reset to `00` when you switch application.

Also, you want `application` to be empty when resetting major/minor/patch, and make `rc` empty in that case as well.

I think you can't have both.

To make `application` reset to empty, put the 'optional_value' as the first option.

```
[bumpversion:part:application]
optional_value = none
values =
        none
	rabbitmq
	lambda
        codedeploy
	devops
```
You can do the same for `rc` but then it won't default to 00 when you switch application.

```
[bumpversion:part:rc]
optional_value = none
values =
	none
	00
        01
	02
        03
```
```
bumpversion bump minor
# from 0.0.1-rabbitmq00 to 0.2.0

bumpversion bump application
# from 0.2.0 to 0.2.0-rabbitmq

bumpversion bump rc
# from 0.2.0-rabbitmq to 0.2.0-rabbitmq00
```

**Comment by florisla** [comment]
@shylaharild OK, don't forget to close this issue then.
