### ISSUE TITLE
Use black to start linting/styling the codebase

### ISSUE THREAD

**Issue by c4urself** [c4urself/bump2version#54]
See: https://github.com/ambv/black

**Comment by florisla** [comment]
Great initiative.

Would you consider using PyLint as well?

In my experience it's great for catching unused variables and arguments, mutable default arguments and stuff like that.  It would catch all occurrences of of `logging-not-lazy` for example, like suggested in #53.

I've found PyLint to to be nicely compatible to `black`.  Just configure the same line-length and disable the 'bad-continuation' message.

You can try this as a not-too-noisy configuration for the current state of the code:

    pylint bumpversion -d missing-docstring,line-too-long,invalid-name,too-few-public-methods,useless-object-inheritance,super-init-not-called,bad-indentation,ungrouped-imports,unused-import,trailing-newlines,wrong-import-order,deprecated-method,too-many-branches,too-many-statements,bad-continuation,fixme

**Comment by florisla** [comment]
Update: pylint was introduced in 7e1ce4da95fb4c95d26be7a4357a4e2cb8fdeb9c .

**Comment by florisla** [comment]
Have you decided against using `black`? (That was the original topic of this issue before I hijacked it by talking about `pylint`).
