### ISSUE TITLE
bumpversion command adds a newline in bumpversion.cfg

### ISSUE THREAD

**Issue by pmav99** [c4urself/bump2version#58]
I am using [pre-commit](https://pre-commit.com/) and one of the hooks I use is is [`end-of-line-fixer`](https://github.com/pre-commit/pre-commit-hooks#hooks-available):

> `end-of-file-fixer` - Makes sure files end in a newline and only a newline.

This seems to be causing issues to bump2version. More specifically, bump2version seems to be adding an extra empty line at the end of `.bumpversion.cfg` which make the hook to fail. As a result, the commit is being aborted.

Is that extra line necessary?

**Comment by avilaton** [comment]
I used the `exclude` field to get around this
```
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
```

**Comment by pmav99** [comment]
@avilaton You are right, this is a viable workaround, but it still seems to be something that could be fixed directly on bump2version

**Comment by arielnmz** [comment]
Related: https://github.com/peritus/bumpversion/issues/179

Patch:

```
Index: bumpversion/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- bumpversion/__init__.py	(date 1435260711000)
+++ bumpversion/__init__.py	(date 1522533107000)
@@ -860,7 +860,7 @@
 
         if write_to_config_file:
             with io.open(config_file, 'wb') as f:
-                f.write(new_config.getvalue().encode('utf-8'))
+                f.write((new_config.getvalue().strip()+'\n').encode('utf-8'))
 
     except UnicodeEncodeError:
         warnings.warn(
```

Don't know if it'd still work

**Comment by jtrakk** [comment]
Nice find, @arielnmz. I just tried that fix and it worked for me.

**Comment by kyluca** [comment]
Opened a new PR heavily inspired by the previous ones here, full credit to the previous authors :)

https://github.com/c4urself/bump2version/pull/98

**Comment by mazzma12** [comment]
https://github.com/mosdef-hub/gmso/pull/602 is 
still an issue for me with version 1.0.1, I had to add an exclude in the pre-commit config
```
    -   id: trailing-whitespace
        exclude: setup.cfg # https://github.com/c4urself/bump2version/issues/58
```
