### ISSUE TITLE
globbing in config file parsing, like [bumpversion:file:*.py]

### ISSUE THREAD

**Issue by rbeyer** [c4urself/bump2version#64]
There was a similar Issue open on the original bumpversion: https://github.com/peritus/bumpversion/issues/104

but it was opened about a month before the last commit on that project.

Perhaps more succinctly composed: the issue is, in addition to having the string after the final ``:`` in ``[bumpversion:file:file_path]`` be interpreted as a strict path, could it be run through the [glob library](https://docs.python.org/3/library/glob.html) or the ``.glob()`` function of [pathlib](https://docs.python.org/3/library/pathlib.html)'s ``Path`` object?  So that the rules in such a section could be applied to multiple files that match the pattern?

Clearly, that's possible, but is there any reason not to implement it?

**Comment by mdfischer** [comment]
I'd also love to see this wildcard functionality.  We have a project with different standalone serverless modules, each in its own subfolder.  So it would be great to be able to specify these as a group in the configuration file, and have the version bump be applied to all files within that folder.

**Comment by c4urself** [comment]
yeah I don't see why not

**Comment by florisla** [comment]
Perhaps this would be a nice syntax: instead of `file`, use `glob`.

    [bumpversion:glob:./*/__init__.py]
    [bumpversion:glob:version*.py]

**Comment by c4urself** [comment]
👍 on the design `glob:<pattern>`
