### ISSUE TITLE
Screencast link in README is dead.

### ISSUE THREAD

**Issue by henniss** [c4urself/bump2version#66]
The screencast link in `README.md`  is dead

https://asciinema.org/a/3828

**Comment by datavistics** [comment]
Just checked and this is still the case.

**Comment by c4urself** [comment]
fair enough, anyone up for making a new one?

**Comment by hugovk** [comment]
The screencast has been removed on https://github.com/c4urself/bump2version/commit/7e1ce4da95fb4c95d26be7a4357a4e2cb8fdeb9c.

Time to close?

**Comment by c4urself** [comment]
yeah may as well...
