### ISSUE TITLE
Config works in `.bumpversion.cfg` but not in `setup.cfg`

### ISSUE THREAD

**Issue by aiguofer** [c4urself/bump2version#77]
Hi, I have a bit of a complex search/replace string for my `CHANGELOG` and was hoping to unify my configs by moving everything into `setup.cfg` and `pyproject.toml` (only would of those would be preferable, but I digress). However, when I move my bumpversion config into `setup.cfg` I keep getting some errors due to the way the `search` and `replace` get parsed out. Here's the relevant section, I imagine I just need to change the formatting but I've tried a bunch of stuff with no success. Any help would be greatly appreciated!

```
[bumpversion:file:CHANGELOG.rst]
search = [Unreleased]
	------------
replace = [Unreleased]
	------------
	[{new_version}] - {now:%Y-%m-%d}
	-----------------------------
```

**Comment by florisla** [comment]
I know I've had to replace `%` (percent sign) with `%%` (double percent sign) in `message` when moving from `bumpversion.cfg` to `setup.cfg`.

So please try that.

If that's not enough, perhaps the `[` square brackets `]` are at fault -- try to escape them in the same fashion.

`{` curly braces `}` don't need escaping.

**Comment by aiguofer** [comment]
Thanks! using double percent sign fixed my problem.
