### ISSUE TITLE
Uploading an sdist

### ISSUE THREAD

**Issue by jtrakk** [c4urself/bump2version#82]
Hi, would you mind uploading an sdist to PyPI in addition to the wheel? That should be

```
python setup.py sdist
twine upload
```

Thank you.

**Comment by florisla** [comment]
This was fixed yesterday.
https://github.com/c4urself/bump2version/commit/b6863ada2e24d80d1e64ecc73d93fc555898e4cb

So you can expect `sdist` packages from the next release on.
