### ISSUE TITLE
Can you append timestamp to a version?

### ISSUE THREAD

**Issue by smorehouse** [c4urself/bump2version#89]
I don't want 2 developers to clobber eachothers artifacts, so it would be helpful if we could version a dev build as "app-name-1.0.2-20190924151024-py2.py3-none-any.whl". Our wheels are created in Jenkins, and then we use twine to put them in Artifactory, so simply incrementing a build number or something similar is a bad idea, as then our devs would have to "git fetch" after every push to a dev branch.

**Comment by florisla** [comment]
I don't think you can do this inside `bump2version` configuration.  There's no timestamp concept nor is there a way to generate arbitrary labels from code.

I would try to do something like this in your `setup.py` file.  If you `import datetime` there, then you can append `datetime.datetime.now().strftime("%Y%m%d%H%M%S")` to your version string.
All the while, keeping this 'addendum' out of your bumpversion config.

**Comment by smorehouse** [comment]
good to know, thanks for the hint!!

**Comment by florisla** [comment]
I just learned about bump2version's support for using environment variables.

So you could pass in the timestamp like this

    export BUILD_TIMESTAMP "20190924151024"

and then use it in your `serialize`

    serialize = {major}.{minor}.{patch}-{$BUILD_TIMESTAMP}

**Comment by c4urself** [comment]
from the docs:
> You can also use the variables now or utcnow to get a current timestamp. Both accept datetime formatting (when used like as in {now:%d.%m.%Y}).
